version: '3.8'

services:
  ros2-humble-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ros2-humble-dev
    container_name: ros2-humble-dev
    tty: true
    stdin_open: true
    ipc: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - "apparmor=unconfined"
    devices:
      - /dev:/dev


    volumes:
      - ./src:/home/dockeruser/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./terminator_config:/home/dockeruser/.config/terminator
      - ./scripts:/home/dockeruser/scripts
      - /var/run/dbus:/var/run/dbus


    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    network_mode: host
