services:
  ros2-humble-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ros2-humble-dev
    container_name: ros2-humble-dev
    tty: true
    stdin_open: true
    ipc: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - "apparmor=unconfined"
    devices:
      - /dev:/dev


    volumes:
      - ./src:/home/dockeruser/ros2_ws/src
      - ./scripts:/home/dockeruser/scripts
      - ./Setup_HSR:/home/dockeruser/ros2_ws/Setup_HSR
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./terminator_config:/home/dockeruser/.config/terminator
      - /var/run/dbus:/var/run/dbus
      # ホストのNVIDIAドライバ関連ライブラリをコンテナにマウント
      - /lib/x86_64-linux-gnu/libGL.so.1:/lib/x86_64-linux-gnu/libGL.so.1
      - /lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
      - /lib/x86_64-linux-gnu/libGLdispatch.so.0:/lib/x86_64-linux-gnu/libGLdispatch.so.0


    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    network_mode: host
